config/routes.rb
TableStorm::Application.routes.draw do
  root :to => "dbs#index"

  match "db_tables" => "db_tables#index"
  match "db_table" => "db_tables#show", :via => "get"

  match "lookupFieldMax" => "db_tables#lookup_field_max"

  match "recent_queries" => "recent_queries#index"

  get "dbs/index"
  get "dbs/edit"
  get "dbs/new"
  post "dbs/create"
  match "dbs/:id" => "dbs#show"

end

app/controllers/db_tables_controller.rb
class DbTablesController < ApplicationController

  def show
    @db = Db.find(params[:db_id])
    logger.debug("### DbTableController#index - db name = #{@db.name} ")

    @table_name = params[:table_name]
    logger.debug("### DbTableController#index - table name = #{@table_name} ")

    @col_name = params[:col_name]
    logger.debug("### DbTableController#index - col name = #{@col_name} ")

    columns = get_columns(@db, @table_name)
    @column_object = columns.detect{ |col| col.name == @col_name}
  end


  def index
    logger.debug("### DbTableController#index - Starting ...")

    @db = Db.find(params[:db_id])
    logger.debug("### DbTableController#index - db name = #{@db.name} ")

    @table_name = params[:table_name]
    logger.debug("### DbTableController#index - table name = #{@table_name} ")

    index_action = params[:index_action] || "none"
    logger.debug("### DbTableController#index - index_action = #{index_action} ")

    @db.recent_queries << RecentQuery.create!(:table_name => @table_name)

    if index_action == "show_data"
      # show actual table values
      @table_rows = get_table_rows(@db, @table_name)
      render "index_data"
    else
      # show just column meta data for now
      @columns = get_columns(@db, @table_name)
    end
  end



  # ajax
  def lookup_field_max
      logger.debug("lookup_field_ma - Starting ...")
      db = Db.find(params[:db_id])
      @col_max = get_field_max(db, params[:table_name], params[:col_name])
      render :lookup_field_max, :layout => false
  end



  def get_field_max(db, table_name, col_name)
    max_col_value = nil
    db_adapter    = "postgresql"   # TODO: make this dynamic
    db_host       = db.host    # TODO: make this dynamic
    db_name       = db.name
    db_username   = db.username
    db_password   = db.password

    active_record_class_name = "#{table_name}".singularize.camelize

    dynamic_class = Class.new(ActiveRecord::Base) do
      self.table_name = table_name
    end
    Kernel.const_set active_record_class_name, dynamic_class

    # db connection
    begin
      conn_est    = dynamic_class.establish_connection(:adapter  => db_adapter, :host => db_host, :username => db_username, :password => db_password, :database => db_name)
      conn        = conn_est.connection   # actually check if connection works
      class_object = Kernel.const_get(active_record_class_name)
      max_col_value = class_object.send(:maximum, col_name) 
      logger.debug("get_field_max - max_col_value = #{max_col_value} ")
    rescue => conn_error
      does_connect = false
      logger.error("get_field_max - ERROR - Message: #{conn_error.message}")
      logger.error("get_field_max - ERROR - Backtrace: #{conn_error.backtrace}")
    end

    max_col_value
  end



  def get_table_rows(db, table_name)
    table_rows = nil
    db_adapter  = "postgresql"   # TODO: make this dynamic
    db_host     = db.host    # TODO: make this dynamic
    db_name     = db.name
    db_username = db.username
    db_password = db.password

    active_record_class_name = "#{table_name}".singularize.camelize
    logger.debug("##### DbTablesController#get_column_names - active_record_class_name = #{active_record_class_name} ")
    dynamic_class = Class.new(ActiveRecord::Base) do
      # self.abstract_class = true
      set_table_name table_name
    end
    Kernel.const_set active_record_class_name, dynamic_class

    # db connection
    begin
      conn_est    = dynamic_class.establish_connection(:adapter  => db_adapter, :host => db_host, :username => db_username, :password => db_password, :database => db_name)
      conn        = conn_est.connection   # actually check if connection works
      class_object = Kernel.const_get(active_record_class_name)
      logger.debug("get_table_rows - class_object = #{class_object.inspect} ")
      columns_hash = class_object.send(:column_names), class_object.send(:columns_hash)
      logger.debug("get_table_rows - columns_hash = #{columns_hash.inspect} ")
      first_column = columns_hash.first.first
      logger.debug("get_table_rows - first_column = #{first_column} ")
      # paginated_rows_array = Kaminari.paginate_array(class_object.send(:order, first_column))
      ### paginated_rows = class_object.send(:order, first_column)
      ### logger.debug("get_table_rows - paginated_rows.class = #{paginated_rows.class} ")
      ### table_rows = paginated_rows.page(params[:page]).per(5)
      table_rows = class_object.send(:order, first_column).page(params[:page]).per(5)
      # logger.debug("get_table_rows - table_rows = #{table_rows.inspect} ")
      # logger.debug("get_table_rows - table_rows.class = #{table_rows.class} ")
      # logger.debug("get_table_rows - table_rows[0] = #{table_rows[0].inspect} ")
      # logger.debug("get_table_rows - table_rows[0].class = #{table_rows[0].class} ")
      logger.debug("get_table_rows - Connection seems to be ok")
    rescue => conn_error
      does_connect = false
      logger.error("get_table_rows - ERROR - Message: #{conn_error.message}")
      logger.error("get_table_rows - ERROR - Backtrace: #{conn_error.backtrace}")
    end

    table_rows
  end



  def get_columns(db, table_name)
    db_adapter  = "postgresql"   # TODO: make this dynamic
    db_host     = db.host    # TODO: make this dynamic
    db_name     = db.name
    db_username = db.username
    db_password = db.password
    table_names = []
    columns = []

    active_record_class_name = "#{table_name}".singularize.camelize
    logger.debug("##### DbTablesController#get_column_names - active_record_class_name = #{active_record_class_name} ")
    dynamic_class = Class.new(ActiveRecord::Base) do
      # self.abstract_class = true
      set_table_name table_name   # some table names may not be pluralized, so set explicitly
    end
    Kernel.const_set active_record_class_name, dynamic_class


    # db connection
    begin
      conn_est    = dynamic_class.establish_connection(:adapter  => db_adapter, :host => db_host, :username => db_username, :password => db_password, :database => db_name)
      conn        = conn_est.connection   # actually check if connection works
      class_object = Kernel.const_get(active_record_class_name)
      logger.debug("get_column_names - class_object = #{class_object.inspect} ")
      # class_object.send(:column_names), class_object.send(:columns_hash)
      columns = class_object.send(:columns)
      logger.debug("get_column_names - columns= #{columns.inspect} ")
      logger.debug("get_column_names - Connection seems to be ok")
    rescue => conn_error
      does_connect = false
      logger.error("get_column_names - ERROR - Message: #{conn_error.message}")
      logger.error("get_column_names - ERROR - Backtrace: #{conn_error.backtrace}")
    end

    columns
  end
end

app/helpers/db_table_helper.rb
module DbTableHelper
end

app/views/db_tables/index.html.erb
<h1>Database Table</h1>

<br />
<hr />

<h3>Database: <%= @db.name %> </h3>

<br />

<h4> &nbsp; Table: <%= @table_name %></h4>

<br />


<p>
  <div id="col-overview">
    <h6>Table column overview:</h6>

    <br />

    <% if @columns.blank? %>
        No columns found
    <% else %>
        <table>
            <% @columns.each do |col| %>
                <tr>
                    <td>
                        <%= col.name %>
                    </td>
                    <td>
                        <%= link_to "Details", db_table_path(:db_id => @db.id, :table_name => @table_name, :col_name => col.name) %>
                    </td>
                </tr>
            <% end %>
        </table>

        <br />
        <br />
        <hr />
        <%= link_to "Show Values", db_tables_path(:db_id => @db.id, :table_name => @table_name, :index_action => "show_data") %>
    <% end %>
  </div>
</p>

app/views/db_tables/index_data.html.erb
<h1>Table Details</h1>

<br />
<hr />

<div id="table-details-db-title">
    <h3>Database: <%= @db.name %></h3>
</div>

<hr />

<h4>
    <span style="font-style:italic;">Table: <%= @table_name %></span>
</h4>

<br />


<p>
    <div id="table-details">
        <%= paginate(@table_rows) %>

        <br />

        <table cellspacing="5" cellpadding="5" style="display: inline; max-width: 50%">
            <tr>
                <%# @table_rows[0].attributes.keys.each do |k| %>
                <%# @table_rows.attributes.keys.each do |k| %>
                <% @table_rows.column_names.each do |col_name| %>
                    <th align="middle">
                        <%= col_name %>
                    </th>
                <% end %>
            </tr>


            <% @table_rows.each do |row| %>
                <tr>
                    <%# row.attributes.values.each do |v| %>
                    <% row.attributes.values.each do |v| %>
                        <td align="left">
                            <%#= row.attributes.inspect.to_s %>
                            <%= v %>
                        </td>
                    <% end %>
                </tr>
            <% end %>
        </table>

        <br />
        <br />
        <br />
        <br />
        <br />

        <%= paginate(@table_rows) %>
    </div>

    <br /><br /><br />
</p>

    <br /><br /><br />

app/views/db_tables/lookup_field_max.erb
Maximum: <%= @col_max %>

app/views/db_tables/show.html.erb
<h1>Column Details</h1>

<br />
<hr />

<p>
  <div id="column-details">
    <table>
        <caption>Column: <%= @column_object.name %>
        <tr>
            <th align="left">
                Rails Type
            </th>
            <td>
                <%= @column_object.type || "N/A"%>
            </td>
        </tr>
        <tr>
            <th align="left">
                SQL Type
            </th>
            <td>
                <%= @column_object.sql_type || "N/A" %>
            </td>
        </tr>
        <tr>
            <th align="left">
                Primary Key
            </th>
            <td>
                <%= @column_object.primary || "N/A" %>
            </td>
        </tr>
        <tr>
            <th align="left">
                Precision
            </th>
            <td>
                <%= @column_object.precision || "N/A" %>
            </td>
        </tr>
        <tr>
            <th align="left">
                Scale
            </th>
            <td>
                <%= @column_object.scale || "N/A" %>
            </td>
        </tr>
    </table>

    <br />

    <div id="ajax-data">
	<div id="result" style="height:50px"> &nbsp;  
          <a href="javascript: lookupMax('<%= @column_object.name %>', '<%= @db.id %>', '<%= @table_name %>');">Maximum</a>
        </div>
    </div>

  </div>
</p>