config/routes.rb
TableStorm::Application.routes.draw do
  root :to => "dbs#index"

  match "db_tables" => "db_tables#index"
  match "db_table" => "db_tables#show", :via => "get"

  match "lookupFieldMax" => "db_tables#lookup_field_max"

  match "recent_queries" => "recent_queries#index"

  get "dbs/index"
  get "dbs/edit"
  get "dbs/new"
  post "dbs/create"
  match "dbs/:id" => "dbs#show"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "Table Storm", root_path, id: "logo" %>
          <% if flash[:notice] %>
              <span style="color: #AA0000; font-size: 1.2em; font-weight:bold; margin-left: 50px;">
                  <%= flash[:notice] %>
              </span>
          <% end %>
          <nav>
            <ul class="nav pull-right">
              <li><%= link_to "Home",      root_path %></li>
              <li><%= link_to "Databases", dbs_index_path %></li>
              <li><%= link_to "Recent",    recent_queries_path %></li>
            </ul>
          </nav>
        </div>
      </div>
    </header>
    <div class="container">
          <br /><br /><br /><br />
      <%= yield %>
    </div>
  </body>
</html>